### ISSUE TITLE
Menü Problem

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.mobile-menu#8]
@signalwerk

Hallo Stefan, ich habe einen Bug in meinem Menü (komplett selber geschrieben) welchen ich nicht beheben kann. Im Menü Overlay hat es in der Alphabetischen-Sortierung einen "Pixelfehler?"

<img width="792" alt="problem_screenshot" src="https://user-images.githubusercontent.com/23292494/51211715-ac2b3b00-1916-11e9-9a31-a535d6e04673.png">

**HTML**
`<div class="scroll_overlay">
        <div class="wrapper_overlay">
          <div class="sorting"><p class="sorting">A</p></div>
          <a class="menu" href="../anonymus/index.html">Anonymous</a>
          <div class="sorting"><p class="sorting">C</p></div>`

**CSS**
```
.scroll_overlay {
    overflow: scroll;
    height: 100vh;
    -webkit-overflow-scrolling: touch;
```

```
.wrapper_overlay {
    padding-left: 20vw;
    padding-right: 20vw;
    margin-top: 100px;
}
```

```
.sorting {
    height: 20px;
    padding: 5px;
    background-color: #6f86d6;
}

```
```
p.sorting {
    font-weight: 600;
    color: white;
    font-size: 1.5rem;
    }
```

```
a.menu {
    font-family: 'Playfair Display', serif;
    font-weight: 400;
    font-size: 2.8rem;
    color: #333333;
    margin-top: 30px;
    margin-bottom: 30px;
    display: block;
    text-decoration: none;
}

```
```
a.menu:hover {
    font-family: 'Playfair Display', serif;
    font-weight: 400;
    font-size: 2.8rem;
    color: #6f86d6;
    margin-top: 30px;
    margin-bottom: 30px;
    display: block;
    text-decoration: none;
}
```

Woran liegt das?  Ich entdecke keinen Fehler.
Eventuell weiss von euch auch jemand eine Lösung ? @logrinto/iad2017 

Merci schon im Voraus.

**Comment by severinkilchhofer** [comment]
Hoi Nils
wäre es so gedacht wie im folgenden Screenshot?

<img width="1167" alt="screenshot nils navigation" src="https://user-images.githubusercontent.com/26141288/51270986-a5f49780-19c6-11e9-8cb0-5fe978709968.png">

**Comment by severinkilchhofer** [comment]
Han dir en Branch gmacht ([https://github.com/logrinto/IAD2017.mobile-menu/tree/nils-menu-fix](nils-menu-fix)) und det de fix ihckeckt.
